name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Inputs
        id: cache-inputs
        uses: actions/cache@v4
        with:
          path: input-cache
          key: input-cache

      - name: Restore Inputs
        id: restore-inputs
        shell: pwsh
        env:
          AOC_SESSION: ${{ secrets.AOC_SESSION }}
        run: ./restore-inputs.ps1 -Verbose -UseCache

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Check code style
        run: dotnet format --no-restore --verify-no-changes

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal
